BEGIN;

INSERT INTO public.permisos (nombre_permiso)
VALUES
  ('INVENTARIO_ALMACENES_VER'),
  ('INVENTARIO_ALMACENES_CREAR'),
  ('INVENTARIO_ALMACENES_EDITAR'),
  ('INVENTARIO_ALMACENES_ELIMINAR'),
  ('INVENTARIO_ALMACENES_ESTADO_CAMBIAR'),
  ('INVENTARIO_PROVEEDORES_VER'),
  ('INVENTARIO_PROVEEDORES_CREAR'),
  ('INVENTARIO_PROVEEDORES_EDITAR'),
  ('INVENTARIO_PROVEEDORES_ELIMINAR'),
  ('INVENTARIO_PROVEEDORES_ESTADO_CAMBIAR'),
  ('INVENTARIO_MOVIMIENTOS_VER'),
  ('INVENTARIO_MOVIMIENTOS_CREAR'),
  ('INVENTARIO_MOVIMIENTOS_EDITAR'),
  ('INVENTARIO_MOVIMIENTOS_ELIMINAR')
ON CONFLICT (nombre_permiso) DO NOTHING;

INSERT INTO public.roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM public.roles r
INNER JOIN public.permisos p
  ON p.nombre_permiso IN (
    'INVENTARIO_ALMACENES_VER',
    'INVENTARIO_ALMACENES_CREAR',
    'INVENTARIO_ALMACENES_EDITAR',
    'INVENTARIO_ALMACENES_ELIMINAR',
    'INVENTARIO_ALMACENES_ESTADO_CAMBIAR',
    'INVENTARIO_PROVEEDORES_VER',
    'INVENTARIO_PROVEEDORES_CREAR',
    'INVENTARIO_PROVEEDORES_EDITAR',
    'INVENTARIO_PROVEEDORES_ELIMINAR',
    'INVENTARIO_PROVEEDORES_ESTADO_CAMBIAR',
    'INVENTARIO_MOVIMIENTOS_VER',
    'INVENTARIO_MOVIMIENTOS_CREAR',
    'INVENTARIO_MOVIMIENTOS_EDITAR',
    'INVENTARIO_MOVIMIENTOS_ELIMINAR'
  )
WHERE lower(trim(r.nombre)) IN ('super_admin', 'super admin')
ON CONFLICT DO NOTHING;

COMMIT;
