-- Clasificacion: POST-SAFE solamente. Usa ::regclass sobre
-- fidelizacion_ajustes_pendientes, tabla que esta migracion puede crear;
-- ejecutar unicamente despues de correr el SAFE companero (si se ejecuta
-- antes y la tabla no existe, las consultas 2/3/4/5/6 fallan por diseno en
-- vez de devolver resultados enganosos).

-- 1) Tabla y columnas esperadas (11 columnas).
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'fidelizacion_ajustes_pendientes'
ORDER BY ordinal_position;

-- 1b) Conteo exacto de columnas: debe ser 11.
SELECT COUNT(*) AS total_columnas
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'fidelizacion_ajustes_pendientes';

-- 2) Constraints (CHECK, UNIQUE, FK, PK) presentes.
SELECT conname, contype, pg_get_constraintdef(oid, true) AS definicion
FROM pg_constraint
WHERE conrelid = 'public.fidelizacion_ajustes_pendientes'::regclass
ORDER BY conname;

-- 3) Indices presentes.
SELECT indexname, indexdef
FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'fidelizacion_ajustes_pendientes'
ORDER BY indexname;

-- 4) Debe estar vacia inmediatamente despues de Fase 1 (ningun codigo de
-- aplicacion escribe en esta tabla todavia).
SELECT COUNT(*) AS filas_existentes FROM public.fidelizacion_ajustes_pendientes;

-- 5) Confirmacion de que las FK apuntan a las tablas correctas, con
-- columna local/referenciada exactas y la accion ON DELETE real
-- (accion_on_delete debe ser 'r' (RESTRICT) o 'a' (NO ACTION) en las 4).
SELECT
  con.conname,
  att2.attname AS columna_local,
  cl2.relname AS tabla_referenciada,
  att.attname AS columna_referenciada,
  con.confdeltype AS accion_on_delete_cruda,
  CASE con.confdeltype
    WHEN 'a' THEN 'NO ACTION'
    WHEN 'r' THEN 'RESTRICT'
    WHEN 'c' THEN 'CASCADE'
    WHEN 'n' THEN 'SET NULL'
    WHEN 'd' THEN 'SET DEFAULT'
    ELSE con.confdeltype::text
  END AS accion_on_delete
FROM pg_constraint con
JOIN pg_class cl ON cl.oid = con.conrelid
JOIN pg_class cl2 ON cl2.oid = con.confrelid
JOIN pg_attribute att ON att.attrelid = con.confrelid AND att.attnum = ANY(con.confkey)
JOIN pg_attribute att2 ON att2.attrelid = con.conrelid AND att2.attnum = ANY(con.conkey)
WHERE con.conrelid = 'public.fidelizacion_ajustes_pendientes'::regclass
  AND con.contype = 'f'
ORDER BY con.conname;

-- 6) Restriccion de coherencia estado/contadores presente y con los tres
-- estados representados en su definicion.
SELECT
  conname,
  pg_get_constraintdef(oid, true) AS definicion,
  pg_get_constraintdef(oid, true) LIKE '%PENDIENTE%' AS incluye_pendiente,
  pg_get_constraintdef(oid, true) LIKE '%PARCIALMENTE_RECUPERADO%' AS incluye_parcial,
  pg_get_constraintdef(oid, true) LIKE '%RECUPERADO%' AS incluye_recuperado
FROM pg_constraint
WHERE conrelid = 'public.fidelizacion_ajustes_pendientes'::regclass
  AND conname = 'ck_fidelizacion_ajustes_pendientes_estado_coherente';

-- 7) Defaults reales por columna, via pg_get_expr(adbin, adrelid)
-- normalizado (sin casts de tipo), igual que el criterio que usa el SAFE.
-- Se esperan: id_ajuste con IDENTITY o nextval(...), puntos_recuperados=0,
-- estado='PENDIENTE', fecha_creacion/fecha_actualizacion=now().
SELECT
  a.attname AS columna,
  a.attidentity AS identity_cruda,
  CASE a.attidentity
    WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
    WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
    ELSE 'sin identity'
  END AS identity,
  trim(regexp_replace(pg_get_expr(d.adbin, d.adrelid), '::[a-zA-Z_ ]+(\(\d+\))?', '', 'g')) AS default_normalizado
FROM pg_attribute a
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE a.attrelid = 'public.fidelizacion_ajustes_pendientes'::regclass
  AND a.attname IN ('id_ajuste', 'puntos_recuperados', 'estado', 'fecha_creacion', 'fecha_actualizacion')
  AND NOT a.attisdropped
ORDER BY a.attnum;

-- 8) Definicion EXACTA de los dos indices simples (columnas en orden, via
-- catalogo pg_index -- no solo indexdef textual), comparable directamente
-- contra lo que el SAFE exige: idx_..._cliente_estado = (id_cliente,
-- estado); idx_..._factura = (id_factura).
SELECT
  ic.relname AS indice,
  string_agg(a.attname, ',' ORDER BY k.ord) AS columnas_en_orden
FROM pg_index i
JOIN pg_class ic ON ic.oid = i.indexrelid
CROSS JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord)
JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = k.attnum
WHERE i.indrelid = 'public.fidelizacion_ajustes_pendientes'::regclass
  AND ic.relname IN (
    'idx_fidelizacion_ajustes_pendientes_cliente_estado',
    'idx_fidelizacion_ajustes_pendientes_factura'
  )
GROUP BY ic.relname
ORDER BY ic.relname;

-- 9) Definicion textual completa de TODOS los indices de la tabla
-- (incluye el indice implicito de la UNIQUE sobre id_reversion), para
-- inspeccion manual adicional.
SELECT indexname, indexdef
FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'fidelizacion_ajustes_pendientes'
ORDER BY indexname;

-- 10) Estado de validacion (convalidated) de TODAS las restricciones de la
-- tabla: todas deben ser true. Una restriccion en false indicaria un
-- ALTER ... NOT VALID que nunca completo su VALIDATE CONSTRAINT.
SELECT conname, contype, convalidated
FROM pg_constraint
WHERE conrelid = 'public.fidelizacion_ajustes_pendientes'::regclass
ORDER BY conname;
