BEGIN;

CREATE TABLE IF NOT EXISTS public.trabajos_impresion_documentos (
  id_documento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_trabajo bigint NOT NULL,
  schema_version smallint NOT NULL,
  tipo_documento text NOT NULL,
  formato text NOT NULL,
  flavor text NOT NULL,
  contenido bytea NOT NULL,
  content_sha256 char(64) NOT NULL,
  content_bytes integer NOT NULL,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT trabajos_impresion_documentos_trabajo_uk UNIQUE (id_trabajo),
  CONSTRAINT trabajos_impresion_documentos_trabajo_fk
    FOREIGN KEY (id_trabajo)
    REFERENCES public.trabajos_impresion(id_trabajo)
    ON DELETE CASCADE,
  CONSTRAINT trabajos_impresion_documentos_schema_chk CHECK (schema_version = 2),
  CONSTRAINT trabajos_impresion_documentos_tipo_chk CHECK (tipo_documento IN ('factura', 'comanda')),
  CONSTRAINT trabajos_impresion_documentos_formato_chk CHECK (
    (tipo_documento = 'factura' AND formato = 'pdf' AND flavor = 'base64')
    OR (tipo_documento = 'comanda' AND formato = 'html' AND flavor = 'plain')
  ),
  CONSTRAINT trabajos_impresion_documentos_hash_chk CHECK (content_sha256 ~ '^[a-f0-9]{64}$'),
  CONSTRAINT trabajos_impresion_documentos_bytes_chk CHECK (
    content_bytes > 0
    AND (
      (tipo_documento = 'factura' AND content_bytes <= 2097152)
      OR (tipo_documento = 'comanda' AND content_bytes <= 262144)
    )
    AND octet_length(contenido) = content_bytes
  )
);

COMMENT ON TABLE public.trabajos_impresion_documentos IS
  'Contenido canonico inmutable de cada trabajo de impresion; acceso exclusivo del backend.';
COMMENT ON COLUMN public.trabajos_impresion_documentos.contenido IS
  'Bytes exactos usados para calcular content_sha256 y content_bytes.';

ALTER TABLE public.trabajos_impresion_documentos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.trabajos_impresion_documentos FROM PUBLIC;
REVOKE ALL ON TABLE public.trabajos_impresion_documentos FROM anon, authenticated;
GRANT SELECT, INSERT ON TABLE public.trabajos_impresion_documentos TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.trabajos_impresion_documentos_id_documento_seq TO service_role;

COMMIT;

-- Verificacion de estructura (ejecutar manualmente despues de aplicar):
-- SELECT column_name,data_type,is_nullable
-- FROM information_schema.columns
-- WHERE table_schema='public' AND table_name='trabajos_impresion_documentos'
-- ORDER BY ordinal_position;

-- Trabajos historicos sin contenido persistido (usan fallback current/legacy):
-- SELECT ti.id_trabajo,ti.tipo_documento,ti.fecha_creacion
-- FROM public.trabajos_impresion ti
-- LEFT JOIN public.trabajos_impresion_documentos tid USING (id_trabajo)
-- WHERE (ti.payload->>'schema_version')::integer = 2 AND tid.id_trabajo IS NULL
-- ORDER BY ti.id_trabajo;

-- Integridad de bytes y descriptor almacenado:
-- SELECT tid.id_trabajo,
--        tid.content_bytes = octet_length(tid.contenido) AS bytes_ok,
--        tid.content_sha256 = encode(digest(tid.contenido, 'sha256'), 'hex') AS hash_ok,
--        tid.content_sha256 = ti.payload->'documento_canonico'->>'content_sha256' AS payload_hash_ok,
--        tid.content_bytes = (ti.payload->'documento_canonico'->>'content_bytes')::integer AS payload_bytes_ok
-- FROM public.trabajos_impresion_documentos tid
-- JOIN public.trabajos_impresion ti USING (id_trabajo)
-- ORDER BY tid.id_trabajo;
